package latexCode;

import java.awt.Graphics2D;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.Iterator;

import javax.swing.JOptionPane;

import accesoBD.Mensajero;

import vista.vistaGrafica.AristaAP;
import vista.vistaGrafica.AristaTuring;
import vista.vistaGrafica.AutomataCanvas;
import vista.vistaGrafica.CurvedArrow;
import vista.vistaGrafica.PanelCentral;

public class LatexCodeConverter {

	private PanelCentral p;	 
	private int xIni1;
	private int xIni2;
	private int yIni;
	private String latex;
	private Mensajero mensajero;

	
	public LatexCodeConverter(PanelCentral panel){
		
		p = panel;
		latex = "";
		mensajero = Mensajero.getInstancia();

	}
	
	public void convertir(){
		generaCodigo();
	}
	
	private void generaCodigo(){
		
		

		AutomataCanvas c = p.getCanvas();
        int numEst = c.getListaEstados().size();
        int numAristas;
        String nombreEstado;
        String tipoAuto = null;
        int coorX;
        int coorY;
        int k = 1;
        int xOrigen;
        int yOrigen;
        int xDestino;
        int yDestino;
        String etiqueta;
        char com = '\"';
        /*String*/ latex = "% Generated by Rocio Barrigüete, Mario Huete\n" +
        "\\documentclass[12pt]{article}\n" +
        "\\input xy\n" +
        "\\xyoption{all}\n" +
        "\\usepackage[all, knot]{xy}\n" +
        "\\xyoption{arc}\n" +
        "\\begin{document}\n" +
        "\\[\n" +
        "\\xy\n\n";
        for(int i = 0; i < numEst; i++){
            nombreEstado = c.getListaEstados().get(i).getEtiqueta();
            coorX = (Math.abs(c.getListaEstados().get(i).getX())*160)/842;
            coorY = (c.getListaEstados().get(i).getY()*160)/783;
            latex = latex + "("+coorX+","+coorY+")*{"+nombreEstado+"};\n";
        }
        for(int i = 0; i < numEst; i++){
            nombreEstado = c.getListaEstados().get(i).getEtiqueta();
            coorX = (Math.abs(c.getListaEstados().get(i).getX())*160)/842;
            coorY = (c.getListaEstados().get(i).getY()*160)/783;
            if(nombreEstado.equals(c.getEstadoInicial())){
                latex = latex + "("+coorX+","+coorY+")*\\xycircle(5.00,5.00){}="+com+nombreEstado+com+";\n";
                xIni1 = coorX-10;
                xIni2 = coorX-5;
                yIni = coorY;
            }
            else if(c.getListaFinales().contains(nombreEstado)){
                latex = latex + "("+coorX+","+coorY+")*\\xycircle(5.00,5.00){--}="+com+nombreEstado+com+";\n";
            }
            else {

                latex = latex + "("+coorX+","+coorY+")*\\xycircle(5.00,5.00){}="+com+nombreEstado+com+";\n";
            }
        }
        latex = latex + "\\ar@{=>}("+xIni1+","+yIni+")*{}; ("+xIni2+","+yIni+")*{}\n";
        /*\ar@/^1pc/^{a}(5,0)*{};(15,0)*{}
        \ar@/^2pc/^{a}(-3,4)*{};(4,3)*{}   %//XXX para loop ^o _ en 2pc*/
        tipoAuto  = p.getPanel().getTipoAutomata();
        if((tipoAuto.equals("AutomataFD"))||(tipoAuto.equals("AutomataFND"))||(tipoAuto.equals("AutomataFNDLambda"))){
        	numAristas = c.getListaAristas().size();
        	for(int j = 0; j < numAristas; j++){
                if(c.getListaAristas().get(j).getOrigen().equals(c.getListaAristas().get(j).getDestino()))
                    k = 2;
                else
                    k = 1;
                xOrigen = (Math.abs(c.getListaAristas().get(j).getX())*160)/842;
                yOrigen = (c.getListaAristas().get(j).getY()*160)/783;
                xDestino = (Math.abs(c.getListaAristas().get(j).getFx())*160)/842;
                yDestino = (c.getListaAristas().get(j).getFy()*160)/783;
                etiqueta = c.getListaAristas().get(j).getEtiqueta();
                latex = latex + "\\ar@/^"+k+"pc/^{"+etiqueta+"}("+xOrigen+
                        ","+yOrigen+")*{};("+xDestino+","+yDestino+")*{}\n";
            }
        }
        if(tipoAuto.equals("AutomataPila")){
        	numAristas = c.getListaAristasPila().size();
        	for(int j = 0; j < numAristas; j++){
                if(c.getListaAristasPila().get(j).getOrigen().equals(c.getListaAristasPila().get(j).getDestino()))
                    k = 2;
                else
                    k = 1;
                xOrigen = (Math.abs(c.getListaAristasPila().get(j).getX())*160)/842;
                yOrigen = (c.getListaAristasPila().get(j).getY()*160)/783;
                xDestino = (Math.abs(c.getListaAristasPila().get(j).getFx())*160)/842;
                yDestino = (c.getListaAristasPila().get(j).getFy()*160)/783;
      //          etiqueta = c.getListaAristasPila().get(j).getEtiqueta();
       /*         latex = latex + "\\ar@/^"+k+"pc/^{"+etiqueta+"}("+xOrigen+
                        ","+yOrigen+")*{};("+xDestino+","+yDestino+")*{}\n";*/
            }
        }
        if(tipoAuto.equals("MaquinaTuring")){
        	
        	
			numAristas = c.getListaAristasTuring().size();
			int j = 0;
			int i = 0;
			String etiquetaAux = "";// String etiqueta = "";
			AristaTuring aristaT = c.getListaAristasTuring().get(i);
			while (i < numAristas){
				
				if ( !aristaT.getMarcada() ){ 
					//Mensajero m=Mensajero.getInstancia();	
					String separador = mensajero.devuelveMensaje("simbolos.separador",4);
					if (etiquetaAux.equals("")){ 
						etiquetaAux = dameEtiqueta(aristaT.getEntradaCinta(),0) + separador + aristaT.getSimboloCinta() + separador + /*dameEtiqueta(*/aristaT.getDireccion()/*)*/;
						j = i+1;
					}
				
					if (j < numAristas){ // falta llave
				
						AristaTuring aux = c.getListaAristasTuring().get(j);
						boolean origen,destinos;		
						destinos = aristaT.getDestino().equals( aux.getDestino());
						origen = aristaT.getOrigen().equals( aux.getOrigen());

						if (destinos && origen && !aux.getMarcada() ) {
							etiquetaAux += " , " + dameEtiqueta(aux.getEntradaCinta(),0) + separador + aux.getSimboloCinta() + separador + /*dameEtiqueta(*/aux.getDireccion()/*SalidaPila())*/;
							aux.setMarcada(true);
						//j++;
						}
					
					}
							
					if	(j >= numAristas){
		
						
						//if(c.getListaAristasTuring().get(j).getOrigen().equals(c.getListaAristasTuring().get(j).getDestino()))
							
							if(aristaT.getOrigen().equals(aristaT.getDestino()))
		                    k = 2;
			                else
			                    k = 1;
							
			                xOrigen = (Math.abs(c.getListaAristasTuring().get(j).getX())*160)/842;
			                yOrigen = (c.getListaAristasTuring().get(j).getY()*160)/783;
			                xDestino = (Math.abs(c.getListaAristasTuring().get(j).getFx())*160)/842;
			                yDestino = (c.getListaAristasTuring().get(j).getFy()*160)/783;
			               // etiqueta = construyeEtiqueta(c.getListaAristasTuring());
			                latex = latex + "\\ar@/^"+k+"pc/^{"+etiquetaAux+"}("+xOrigen+
			                        ","+yOrigen+")*{};("+xDestino+","+yDestino+")*{}\n";
						
					}
				}
				
				if (j >= numAristas){ 
					i++; 
					j = i+1;  
					etiquetaAux = "";
					if (i < numAristas) 	aristaT = c.getListaAristasTuring().get(i);
				}
				else j++; 
			}

        }
        
        latex = latex + "\\endxy\n" +
                "\\]\n" +
                "\\end{document}\n";
       System.out.println(latex);
	   creaArchivo();	
	}
	
	
	// 0 para simbolos, 1 para transicion de pila
	private String dameEtiqueta(ArrayList<String> a, int tipo){
	
		Iterator<String> it = a.iterator();
		String r = it.next();
		while (it.hasNext()){
			if (tipo == 0)
				r+=",";
			//else r+=
			r += it.next();
		}
		return r;
	}
	
	
	
	private void creaArchivo(){
		
	    try {
	    	// Apertura del fichero y creacion de BufferedReader para poder
	        // hacer una lectura comoda (disponer del metodo readLine()).
    		
    		PrintWriter pw = null;
    		String ruta = "LaTeX/"+"CLaTeX.tex";
    		FileWriter fichero = new FileWriter(ruta);
			pw = new PrintWriter(fichero);

            pw.println(latex);
            muestraTex(ruta);
            pw.close();
	    }

    	catch(Exception e){
    		e.printStackTrace();
    	}
	}
	
	public void muestraTex(String ruta){
		
			Mensajero m= mensajero;
			String url=ruta;
			String osName = System.getProperty("os.name");
		      try {
		         if (osName.startsWith("Mac OS")) {
		            Class<?> fileMgr = Class.forName("com.apple.eio.FileManager");
		            Method openURL = fileMgr.getDeclaredMethod("openURL",
		               new Class[] {String.class});
		            openURL.invoke(null, new Object[] {url});
		            }
		         else if (osName.startsWith("Windows"))
		            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + url);
		         else { //assume Unix or Linux
		            String[] browsers = {"TeXnicsCenter", "TeXworks", "Winedt","Kile"};
		            String browser = null;
		            for (int count = 0; count < browsers.length && browser == null; count++)
		               if (Runtime.getRuntime().exec(
		                     new String[] {"which", browsers[count]}).waitFor() == 0)
		                  browser = browsers[count];
		            if (browser == null) {
		            	JOptionPane.showMessageDialog(null,m.devuelveMensaje("vista.navegador", 2),"Error",JOptionPane.ERROR_MESSAGE);
		            } else {
		               Runtime.getRuntime().exec(new String[] {browser, url});
		            }
		         }
		      }
		      catch (Exception e) {
		    	  JOptionPane.showMessageDialog(null,m.devuelveMensaje("vista.ejecucion", 2),"Error",JOptionPane.ERROR_MESSAGE);
		      }
		
	}
	
}
